/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/fixtures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Fixtures
         * @description Fikstür ve sonuçlar: başlama zamanına göre sıralı. `from` verilirse o günden itibaren
         *     (saati belli olmayan planlı maçlar dahil).
         */
        get: operations["listFixtures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Imports */
        get: operations["listImports"];
        put?: never;
        /** Create Import */
        post: operations["createImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import */
        get: operations["getImport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{import_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit Import
         * @description Doğrulanmış içe aktarımı kiracının tablolarına yazar. Karantinadaki ya da takım onayı
         *     bekleyen içe aktarım 409 alır.
         */
        post: operations["commitImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{import_id}/mapping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Mapping
         * @description Sütun ya da takım eşleştirmesini değiştirir; dosya yeniden doğrulanır.
         */
        put: operations["updateImportMapping"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ingestion Runs */
        get: operations["listIngestionRuns"];
        put?: never;
        /** Create Ingestion Run */
        post: operations["createIngestionRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingestion Run */
        get: operations["getIngestionRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routine-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["listRoutineTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Routines */
        get: operations["listRoutines"];
        put?: never;
        /** Create Routine */
        post: operations["createRoutine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routines/from-template/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create From Template */
        post: operations["createRoutineFromTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routines/{routine_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Routine */
        get: operations["getRoutine"];
        /** Update Routine */
        put: operations["updateRoutine"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Routine */
        patch: operations["patchRoutine"];
        trace?: never;
    };
    "/api/v1/routines/{routine_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["listRoutineVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routines/{routine_id}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version */
        get: operations["getRoutineVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Seasons */
        get: operations["listSeasons"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons/{season_id}/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Benchmarks
         * @description Lig kıyasları: metrik başına en düşük, en yüksek ve ortalama; lig toplamları; aynı sezonun
         *     kayıttaki referans kıyasları (ör. Premier League).
         */
        get: operations["getBenchmarks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons/{season_id}/standings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Standings
         * @description Puan durumu. `week` verilmezse kayıttaki son hafta.
         */
        get: operations["getStandings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons/{season_id}/team-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Team Metrics
         * @description Takım başına sezon metrikleri: değer, lig sırası, yüzdelik, büzülmüş değer, az veri ve
         *     kaynak (SPEC §6). Takım koduna göre sıralı.
         */
        get: operations["listTeamMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Team Profile
         * @description Takım profili: metrikler ve sıralar, lig kıyasları, kendi kulübümüzün değerleri, son puan
         *     durumu satırı ve son 5 maçın formu.
         */
        get: operations["getTeamProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/set-pieces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Team Set Pieces
         * @description Takımın sezondaki duran top dizileri (olay verisi ya da kulübün kendi kaydı).
         */
        get: operations["listTeamSetPieces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveTenantOut */
        ActiveTenantOut: {
            /** Permissions */
            permissions: {
                [key: string]: "all" | "summary" | "own";
            };
            /** Roles */
            roles: components["schemas"]["Role"][];
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Tenant Name */
            tenant_name: string;
        };
        /** BenchmarkOut */
        BenchmarkOut: {
            /** Max */
            max: number;
            /** Mean */
            mean: number;
            /** Min */
            min: number;
            /** Teams */
            teams: number;
        };
        /** BenchmarksOut */
        BenchmarksOut: {
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["BenchmarkOut"];
            };
            /** References */
            references: components["schemas"]["ReferenceOut"][];
            /**
             * Season Id
             * Format: uuid
             */
            season_id: string;
            /** Totals */
            totals: {
                [key: string]: number;
            };
        };
        /** Body_createImport */
        Body_createImport: {
            /** File */
            file: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "team_season_stats" | "events";
            /**
             * Season Id
             * Format: uuid
             */
            season_id: string;
        };
        /** CompetitionRef */
        CompetitionRef: {
            /** Code */
            code: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * Diagram
         * @description Bir rutin sürümünün çizimi.
         */
        Diagram: {
            /** Ball */
            ball?: [
                number,
                number
            ] | null;
            /** Frames */
            frames?: components["schemas"]["DiagramFrame"][];
            /** Lines */
            lines?: components["schemas"]["DiagramLine"][];
            /** Players */
            players?: components["schemas"]["DiagramPlayer"][];
            /**
             * Schema
             * @default 1
             * @constant
             */
            schema: 1;
            /** Zones */
            zones?: components["schemas"]["DiagramZone"][];
        };
        /** DiagramFrame */
        DiagramFrame: {
            /** Ball */
            ball?: [
                number,
                number
            ] | null;
            /**
             * Duration Ms
             * @default 1000
             */
            duration_ms: number;
            /** Id */
            id: string;
            /** Positions */
            positions?: {
                [key: string]: [
                    number,
                    number
                ];
            };
        };
        /** DiagramLine */
        DiagramLine: {
            /**
             * Curve
             * @default 0
             */
            curve: number;
            /** From */
            from: [
                number,
                number
            ];
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "run" | "ball_path" | "screen";
            /** Player Id */
            player_id?: string | null;
            /** To */
            to: [
                number,
                number
            ];
        };
        /** DiagramPlayer */
        DiagramPlayer: {
            /** Id */
            id: string;
            /** Label */
            label?: string | null;
            /** Number */
            number?: number | null;
            /** Role */
            role: string;
            /**
             * Team
             * @enum {string}
             */
            team: "own" | "opponent";
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** DiagramZone */
        DiagramZone: {
            /** H */
            h: number;
            /** Id */
            id: string;
            /** Label */
            label?: string | null;
            /** W */
            w: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** FieldOut */
        FieldOut: {
            /** Name */
            name: string;
            /** Required */
            required: boolean;
        };
        /** FixtureOut */
        FixtureOut: {
            away: components["schemas"]["TeamRef"];
            /** Away Score */
            away_score: number | null;
            home: components["schemas"]["TeamRef"];
            /** Home Score */
            home_score: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kickoff At */
            kickoff_at: string | null;
            /**
             * Season Id
             * Format: uuid
             */
            season_id: string;
            /** Status */
            status: string;
            /** Week */
            week: number | null;
        };
        /** FixturePage */
        FixturePage: {
            /** Items */
            items: components["schemas"]["FixtureOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** FormOut */
        FormOut: {
            /** Goals Against */
            goals_against: number;
            /** Goals For */
            goals_for: number;
            /** Home */
            home: boolean;
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            opponent: components["schemas"]["TeamRef"];
            /**
             * Result
             * @enum {string}
             */
            result: "W" | "D" | "L";
            /** Week */
            week: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Checks
             * @default {}
             */
            checks: {
                [key: string]: boolean;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /** ImportOut */
        ImportOut: {
            /** Columns */
            columns: {
                [key: string]: string | null;
            };
            /** Committed At */
            committed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Fields */
            fields: components["schemas"]["FieldOut"][];
            /** File Columns */
            file_columns: string[];
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "team_season_stats" | "events";
            /** Report */
            report: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Sample */
            sample: {
                [key: string]: string;
            }[];
            /** Season Id */
            season_id: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Status */
            status: string;
            /** Team Options */
            team_options: components["schemas"]["TeamOption"][];
            /** Teams */
            teams: components["schemas"]["TeamMatchOut"][];
        };
        /** ImportSummary */
        ImportSummary: {
            /** Committed At */
            committed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "team_season_stats" | "events";
            /** Season Id */
            season_id: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Status */
            status: string;
        };
        /** IngestionRunCreate */
        IngestionRunCreate: {
            params: components["schemas"]["StatsBombParams"];
            /**
             * Provider
             * @constant
             */
            provider: "statsbomb_open";
        };
        /** IngestionRunOut */
        IngestionRunOut: {
            /** Error */
            error: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Provider */
            provider: string;
            /** Quality Report */
            quality_report: {
                [key: string]: unknown;
            } | null;
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
        };
        /** MappingUpdate */
        MappingUpdate: {
            /**
             * Columns
             * @description Dosya sütunu → şablon alanı (`null`: yok say)
             */
            columns?: {
                [key: string]: string | null;
            } | null;
            /**
             * Teams
             * @description Dosyadaki takım adı → takım kimliği (`null`: seçimi kaldır)
             */
            teams?: {
                [key: string]: string | null;
            } | null;
        };
        /** MeOut */
        MeOut: {
            active_tenant: components["schemas"]["ActiveTenantOut"] | null;
            /** Email */
            email: string | null;
            /** Memberships */
            memberships: components["schemas"]["MembershipOut"][];
            /** Name */
            name: string | null;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** MembershipOut */
        MembershipOut: {
            /** Roles */
            roles: components["schemas"]["Role"][];
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Tenant Name */
            tenant_name: string;
        };
        /**
         * MetricValueOut
         * @description Bir takımın bir metrikteki değeri (SPEC §6.1, §6.4).
         */
        MetricValueOut: {
            /** Approx */
            approx: boolean;
            /** Indirect */
            indirect: boolean;
            /** Low Sample */
            low_sample: boolean;
            /** Matches */
            matches: number | null;
            /** Percentile */
            percentile: number | null;
            /** Rank */
            rank: number;
            /** Shrunk */
            shrunk: number | null;
            /** Shrunk High */
            shrunk_high: number | null;
            /** Shrunk Low */
            shrunk_low: number | null;
            /** Source */
            source: string;
            /** Teams */
            teams: number;
            /** Trials */
            trials: number | null;
            /** Value */
            value: number;
        };
        /**
         * Permission
         * @enum {string}
         */
        Permission: "read_analysis" | "edit_routines" | "decide_recommendations" | "mark_plan_items" | "live_tagging_video" | "load_wellness" | "medical_notes" | "rule_settings" | "user_admin_audit" | "player_cards";
        /**
         * RateOut
         * @description Oran ve beta-binom büzülmesi (SPEC §6.4).
         */
        RateOut: {
            /** High */
            high: number | null;
            /** Low */
            low: number | null;
            /** Shrunk */
            shrunk: number | null;
            /** Trials */
            trials: number;
            /** Value */
            value: number | null;
        };
        /** ReferenceOut */
        ReferenceOut: {
            competition: components["schemas"]["CompetitionRef"];
            /** Metric */
            metric: string;
            /** Season Code */
            season_code: string;
            /** Source */
            source: string;
            /** Value */
            value: number;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "admin" | "head_coach" | "sp_coach" | "analyst" | "performance" | "medical" | "player" | "viewer";
        /** RoutineCreate */
        RoutineCreate: {
            diagram?: components["schemas"]["Diagram"];
            /**
             * Is Defensive
             * @default false
             */
            is_defensive: boolean;
            /** Name */
            name: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Side */
            side?: ("left" | "right") | null;
            /**
             * Sp Type
             * @enum {string}
             */
            sp_type: "corner" | "free_kick" | "throw_in";
            /**
             * When To Use
             * @default
             */
            when_to_use: string;
        };
        /** RoutineFromTemplate */
        RoutineFromTemplate: {
            /** Name */
            name?: string | null;
        };
        /** RoutineOut */
        RoutineOut: {
            /** Archived */
            archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Version */
            current_version: number;
            /** From Template */
            from_template: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Defensive */
            is_defensive: boolean;
            /** Name */
            name: string;
            /** Side */
            side: ("left" | "right") | null;
            /**
             * Sp Type
             * @enum {string}
             */
            sp_type: "corner" | "free_kick" | "throw_in";
            stats: components["schemas"]["RoutineStatsOut"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            version: components["schemas"]["VersionOut"];
        };
        /** RoutinePage */
        RoutinePage: {
            /** Items */
            items: components["schemas"]["RoutineSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** RoutinePatch */
        RoutinePatch: {
            /** Archived */
            archived: boolean;
        };
        /**
         * RoutineStatsOut
         * @description Rutin performansı (SPEC §6.3). Rutine bağlı duran top dizilerinden (A-44).
         */
        RoutineStatsOut: {
            first_contact: components["schemas"]["RateOut"];
            /** Goals */
            goals: number;
            /** Low Sample */
            low_sample: boolean;
            /** Matches */
            matches: number;
            shot: components["schemas"]["RateOut"];
            /** Uses */
            uses: number;
            /** Xg */
            xg: number;
            /** Xg Per Use */
            xg_per_use: number | null;
        };
        /** RoutineSummary */
        RoutineSummary: {
            /** Archived */
            archived: boolean;
            /** Current Version */
            current_version: number;
            diagram: components["schemas"]["Diagram"];
            /** From Template */
            from_template: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Defensive */
            is_defensive: boolean;
            /** Name */
            name: string;
            /** Side */
            side: ("left" | "right") | null;
            /**
             * Sp Type
             * @enum {string}
             */
            sp_type: "corner" | "free_kick" | "throw_in";
            stats: components["schemas"]["RoutineStatsOut"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            updated_by: components["schemas"]["UserRef"] | null;
        };
        /**
         * RoutineUpdate
         * @description Yeni sürüm. `base_version` güncel sürüm değilse 409 (A-41).
         */
        RoutineUpdate: {
            /** Base Version */
            base_version: number;
            diagram: components["schemas"]["Diagram"];
            /** Message */
            message?: string | null;
            /** Name */
            name: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Side */
            side?: ("left" | "right") | null;
            /**
             * When To Use
             * @default
             */
            when_to_use: string;
        };
        /** SeasonOut */
        SeasonOut: {
            /** Code */
            code: string;
            competition: components["schemas"]["CompetitionRef"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Matches Per Team */
            matches_per_team: number | null;
        };
        /** SeasonPage */
        SeasonPage: {
            /** Items */
            items: components["schemas"]["SeasonOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** SetPieceOut */
        SetPieceOut: {
            /** First Contact Team Id */
            first_contact_team_id: string | null;
            /** Goal */
            goal: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            opponent: components["schemas"]["TeamRef"];
            /** Outcome */
            outcome: string | null;
            /** Period */
            period: number;
            /** Phase Of Goal */
            phase_of_goal: number | null;
            /** Shots */
            shots: number;
            /** Side */
            side: string | null;
            /** Source */
            source: string;
            /** Sp Subtype */
            sp_subtype: string | null;
            /** Sp Type */
            sp_type: string;
            /** Start Time S */
            start_time_s: number;
            /** Target Zone */
            target_zone: string | null;
            /** Week */
            week: number | null;
            /** Xg Total */
            xg_total: number;
        };
        /** SetPiecePage */
        SetPiecePage: {
            /** Items */
            items: components["schemas"]["SetPieceOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** StandingRowOut */
        StandingRowOut: {
            /** Drawn */
            drawn: number;
            /** Ga */
            ga: number;
            /** Gf */
            gf: number;
            /** Lost */
            lost: number;
            /** Played */
            played: number;
            /** Position */
            position: number;
            /** Pts */
            pts: number;
            team: components["schemas"]["TeamRef"];
            /** Won */
            won: number;
        };
        /** StandingsOut */
        StandingsOut: {
            /** Rows */
            rows: components["schemas"]["StandingRowOut"][];
            /**
             * Season Id
             * Format: uuid
             */
            season_id: string;
            /** Source */
            source: string;
            /** Week */
            week: number;
        };
        /** StatsBombParams */
        StatsBombParams: {
            /** Competition Id */
            competition_id: number;
            /** Limit */
            limit?: number | null;
            /** Reprocess */
            reprocess?: boolean | null;
            /** Season Id */
            season_id: number;
        };
        /** TeamMatchOut */
        TeamMatchOut: {
            /** Confirmed */
            confirmed: boolean;
            /** Manual */
            manual: boolean;
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Suggested */
            suggested: string | null;
            /** Team Id */
            team_id: string | null;
        };
        /** TeamMetricsOut */
        TeamMetricsOut: {
            /** As Of Week */
            as_of_week: number | null;
            /** Inputs */
            inputs: {
                [key: string]: number;
            };
            team: components["schemas"]["TeamRef"];
            /** Values */
            values: {
                [key: string]: components["schemas"]["MetricValueOut"];
            };
        };
        /** TeamMetricsPage */
        TeamMetricsPage: {
            /** Club Team Id */
            club_team_id: string | null;
            /** Items */
            items: components["schemas"]["TeamMetricsOut"][];
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Season Id
             * Format: uuid
             */
            season_id: string;
        };
        /** TeamOption */
        TeamOption: {
            /** Code */
            code: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** TeamOut */
        TeamOut: {
            /** Code */
            code: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Official Name */
            official_name: string | null;
        };
        /** TeamProfileOut */
        TeamProfileOut: {
            /** As Of Week */
            as_of_week: number | null;
            /** Benchmarks */
            benchmarks: {
                [key: string]: components["schemas"]["BenchmarkOut"];
            };
            club: components["schemas"]["TeamRef"] | null;
            /** Club Values */
            club_values: {
                [key: string]: components["schemas"]["MetricValueOut"];
            };
            /** Form */
            form: components["schemas"]["FormOut"][];
            season: components["schemas"]["SeasonOut"];
            standing: components["schemas"]["StandingRowOut"] | null;
            /** Standing Week */
            standing_week: number | null;
            team: components["schemas"]["TeamOut"];
            /** Values */
            values: {
                [key: string]: components["schemas"]["MetricValueOut"];
            };
        };
        /** TeamRef */
        TeamRef: {
            /** Code */
            code: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** TemplateOut */
        TemplateOut: {
            diagram: components["schemas"]["Diagram"];
            /** Id */
            id: string;
            /** Is Defensive */
            is_defensive: boolean;
            /** Name */
            name: string;
            /** Notes */
            notes: string;
            /** Side */
            side: ("left" | "right") | null;
            /**
             * Sp Type
             * @enum {string}
             */
            sp_type: "corner" | "free_kick" | "throw_in";
            /** When To Use */
            when_to_use: string;
        };
        /** UserRef */
        UserRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionOut */
        VersionOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            created_by: components["schemas"]["UserRef"] | null;
            diagram: components["schemas"]["Diagram"];
            /** Message */
            message: string | null;
            /** Name */
            name: string;
            /** Notes */
            notes: string;
            /** Side */
            side: ("left" | "right") | null;
            /** Version */
            version: number;
            /** When To Use */
            when_to_use: string;
        };
        /** VersionSummary */
        VersionSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            created_by: components["schemas"]["UserRef"] | null;
            /** Message */
            message: string | null;
            /** Name */
            name: string;
            /** Version */
            version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listFixtures: {
        parameters: {
            query?: {
                team?: string | null;
                season?: string | null;
                from?: string | null;
                status?: ("scheduled" | "finished") | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixturePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listImports: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createImport: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Kurgu-Tenant"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_createImport"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getImport: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commitImport: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateImportMapping: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listIngestionRuns: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createIngestionRun: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestionRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getIngestionRun: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRoutineTemplates: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRoutines: {
        parameters: {
            query?: {
                type?: ("corner" | "free_kick" | "throw_in") | null;
                archived?: boolean;
                q?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutinePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createRoutine: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createRoutineFromTemplate: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RoutineFromTemplate"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRoutine: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                routine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateRoutine: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                routine_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description `base_version` is not the current version */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patchRoutine: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                routine_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutinePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRoutineVersions: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                routine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRoutineVersion: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                routine_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSeasons: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getBenchmarks: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                season_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarksOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getStandings: {
        parameters: {
            query?: {
                week?: number | null;
            };
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                season_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listTeamMetrics: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                season_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMetricsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getTeamProfile: {
        parameters: {
            query: {
                /** @description Sezon kimliği */
                season: string;
            };
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listTeamSetPieces: {
        parameters: {
            query: {
                /** @description Sezon kimliği */
                season: string;
                /** @description Duran top türü */
                type?: ("corner" | "free_kick" | "throw_in") | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetPiecePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
