/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Imports */
        get: operations["listImports"];
        put?: never;
        /** Create Import */
        post: operations["createImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import */
        get: operations["getImport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{import_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit Import
         * @description Doğrulanmış içe aktarımı kiracının tablolarına yazar. Karantinadaki ya da takım onayı
         *     bekleyen içe aktarım 409 alır.
         */
        post: operations["commitImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{import_id}/mapping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Mapping
         * @description Sütun ya da takım eşleştirmesini değiştirir; dosya yeniden doğrulanır.
         */
        put: operations["updateImportMapping"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ingestion Runs */
        get: operations["listIngestionRuns"];
        put?: never;
        /** Create Ingestion Run */
        post: operations["createIngestionRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingestion Run */
        get: operations["getIngestionRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Seasons */
        get: operations["listSeasons"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons/{season_id}/standings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Standings
         * @description Puan durumu. `week` verilmezse kayıttaki son hafta.
         */
        get: operations["getStandings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons/{season_id}/team-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Team Metrics
         * @description Takım başına sezon metrikleri (ham kayıt değerleri), takım koduna göre sıralı.
         */
        get: operations["listTeamMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Team Profile
         * @description Takım profili: sezon metrikleri ve son puan durumu satırı (Faz 1: ham değerler).
         */
        get: operations["getTeamProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveTenantOut */
        ActiveTenantOut: {
            /** Permissions */
            permissions: {
                [key: string]: "all" | "summary" | "own";
            };
            /** Roles */
            roles: components["schemas"]["Role"][];
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Tenant Name */
            tenant_name: string;
        };
        /** Body_createImport */
        Body_createImport: {
            /** File */
            file: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "team_season_stats" | "events";
            /**
             * Season Id
             * Format: uuid
             */
            season_id: string;
        };
        /** CompetitionRef */
        CompetitionRef: {
            /** Code */
            code: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** FieldOut */
        FieldOut: {
            /** Name */
            name: string;
            /** Required */
            required: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Checks
             * @default {}
             */
            checks: {
                [key: string]: boolean;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /** ImportOut */
        ImportOut: {
            /** Columns */
            columns: {
                [key: string]: string | null;
            };
            /** Committed At */
            committed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Fields */
            fields: components["schemas"]["FieldOut"][];
            /** File Columns */
            file_columns: string[];
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "team_season_stats" | "events";
            /** Report */
            report: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Sample */
            sample: {
                [key: string]: string;
            }[];
            /** Season Id */
            season_id: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Status */
            status: string;
            /** Team Options */
            team_options: components["schemas"]["TeamOption"][];
            /** Teams */
            teams: components["schemas"]["TeamMatchOut"][];
        };
        /** ImportSummary */
        ImportSummary: {
            /** Committed At */
            committed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "team_season_stats" | "events";
            /** Season Id */
            season_id: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Status */
            status: string;
        };
        /** IngestionRunCreate */
        IngestionRunCreate: {
            params: components["schemas"]["StatsBombParams"];
            /**
             * Provider
             * @constant
             */
            provider: "statsbomb_open";
        };
        /** IngestionRunOut */
        IngestionRunOut: {
            /** Error */
            error: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Provider */
            provider: string;
            /** Quality Report */
            quality_report: {
                [key: string]: unknown;
            } | null;
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
        };
        /** MappingUpdate */
        MappingUpdate: {
            /**
             * Columns
             * @description Dosya sütunu → şablon alanı (`null`: yok say)
             */
            columns?: {
                [key: string]: string | null;
            } | null;
            /**
             * Teams
             * @description Dosyadaki takım adı → takım kimliği (`null`: seçimi kaldır)
             */
            teams?: {
                [key: string]: string | null;
            } | null;
        };
        /** MeOut */
        MeOut: {
            active_tenant: components["schemas"]["ActiveTenantOut"] | null;
            /** Email */
            email: string | null;
            /** Memberships */
            memberships: components["schemas"]["MembershipOut"][];
            /** Name */
            name: string | null;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** MembershipOut */
        MembershipOut: {
            /** Roles */
            roles: components["schemas"]["Role"][];
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Tenant Name */
            tenant_name: string;
        };
        /**
         * Permission
         * @enum {string}
         */
        Permission: "read_analysis" | "edit_routines" | "decide_recommendations" | "mark_plan_items" | "live_tagging_video" | "load_wellness" | "medical_notes" | "rule_settings" | "user_admin_audit" | "player_cards";
        /**
         * Role
         * @enum {string}
         */
        Role: "admin" | "head_coach" | "sp_coach" | "analyst" | "performance" | "medical" | "player" | "viewer";
        /** SeasonOut */
        SeasonOut: {
            /** Code */
            code: string;
            competition: components["schemas"]["CompetitionRef"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Matches Per Team */
            matches_per_team: number | null;
        };
        /** SeasonPage */
        SeasonPage: {
            /** Items */
            items: components["schemas"]["SeasonOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** StandingRowOut */
        StandingRowOut: {
            /** Drawn */
            drawn: number;
            /** Ga */
            ga: number;
            /** Gf */
            gf: number;
            /** Lost */
            lost: number;
            /** Played */
            played: number;
            /** Position */
            position: number;
            /** Pts */
            pts: number;
            team: components["schemas"]["TeamRef"];
            /** Won */
            won: number;
        };
        /** StandingsOut */
        StandingsOut: {
            /** Rows */
            rows: components["schemas"]["StandingRowOut"][];
            /**
             * Season Id
             * Format: uuid
             */
            season_id: string;
            /** Source */
            source: string;
            /** Week */
            week: number;
        };
        /** StatsBombParams */
        StatsBombParams: {
            /** Competition Id */
            competition_id: number;
            /** Limit */
            limit?: number | null;
            /** Reprocess */
            reprocess?: boolean | null;
            /** Season Id */
            season_id: number;
        };
        /** TeamMatchOut */
        TeamMatchOut: {
            /** Confirmed */
            confirmed: boolean;
            /** Manual */
            manual: boolean;
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Suggested */
            suggested: string | null;
            /** Team Id */
            team_id: string | null;
        };
        /** TeamMetricsOut */
        TeamMetricsOut: {
            /** As Of Week */
            as_of_week: number | null;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            /** Source */
            source: string;
            team: components["schemas"]["TeamRef"];
        };
        /** TeamMetricsPage */
        TeamMetricsPage: {
            /** Items */
            items: components["schemas"]["TeamMetricsOut"][];
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Season Id
             * Format: uuid
             */
            season_id: string;
        };
        /** TeamOption */
        TeamOption: {
            /** Code */
            code: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** TeamOut */
        TeamOut: {
            /** Code */
            code: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Official Name */
            official_name: string | null;
        };
        /** TeamProfileOut */
        TeamProfileOut: {
            /** As Of Week */
            as_of_week: number | null;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            season: components["schemas"]["SeasonOut"];
            /** Source */
            source: string | null;
            standing: components["schemas"]["StandingRowOut"] | null;
            /** Standing Week */
            standing_week: number | null;
            team: components["schemas"]["TeamOut"];
        };
        /** TeamRef */
        TeamRef: {
            /** Code */
            code: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listImports: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createImport: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Kurgu-Tenant"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_createImport"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getImport: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commitImport: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateImportMapping: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listIngestionRuns: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createIngestionRun: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestionRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getIngestionRun: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSeasons: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getStandings: {
        parameters: {
            query?: {
                week?: number | null;
            };
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                season_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listTeamMetrics: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                season_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMetricsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getTeamProfile: {
        parameters: {
            query: {
                /** @description Sezon kimliği */
                season: string;
            };
            header?: {
                "X-Kurgu-Tenant"?: string | null;
            };
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
